### ISSUE TITLE
Facebook & Instagram Content - March 2023

### ISSUE THREAD

**Issue by kaycix** [kaycix/northcoastcnpsnursery#2]
A list of content for our Facebook and Instagram posts for March 2023.

**Comment by kaycix** [comment]
**March Plant of the Month**

![Red_flowering_currant_Arcata_marsh](https://user-images.githubusercontent.com/2887265/223780032-409e9a52-e8f9-488e-9a5f-2cc465099884.jpeg)

Sample text: 
Time for our March Plant of the Month!

We're starting to see little beacons of Spring, like in this Red Flowering Currant (Ribes sanguineum). 

Keep an eye out for this beautiful shrub when you're out and about. The showy pink flowers really stand out this time of year ... especially THIS year while everything else is still lying dormant in the c-c-cold. 

This photo was taken last week at the Arcata Marsh native plant garden. 

Photo by Nursery Manager Barbara (also an Arcata Marsh docent and Lanphere Dunes docent/enthusiast).
Check out our nursery at: 
https://northcoastcnpsnursery.org

**Comment by kaycix** [comment]
### Yarrow Native Lawn Mix

(Private backstory - I was walking with a friend who pointed out this yard that her husband worked on, which is why I was able to get the inside scoop from him). 

**Sample text:** 
Look! A native yarrow mix lawn. 
It’s not quite what you thought a native lawn replacement would look like, right? 

This sweet little native lawn resides at private residence in Arcata.

It’s perfect for those who want to hold onto their lawn but also want to live by their values of being in balance with nature. Wouldn’t you love to see lawns, public areas, and golf courses do the same?

Feeling inspired? Here's a little more detail. 

This Yarrow Mix Lawn was planted via hydro seeding method in Spring 2023 by Miller Farms Nursery. 

This particular native mix was designed and specified by Jessica Hall, of Wildling Design Studio. 

Jessica specializes in native plantings and she designed the entire site planting with local native species. 

And here’s her recipe: 
Common Yarrow,  California Brome-Grass, California Oatgrass, Coastal Larkspur, Red Fescue, Beach Strawberry, Sky Lupine, Checkerbloom

Planting native doesn’t mean giving up entirely on the things we’re used to. 
But it does require us to break decades-old patterns. And tbh it’s kind of a win-win, native plants support biodiversity, while often being more low-maintenance. 

**Images**
![yarrow_at_nursery](https://user-images.githubusercontent.com/2887265/223782557-a75591a0-814e-4ac4-8970-844624680244.jpg)
![yarrow_lawn](https://user-images.githubusercontent.com/2887265/223782600-fb8a111d-5673-464c-b33b-0f60bf98f275.JPG)

**Comment by kaycix** [comment]
### Post Idea: 
Let's get a little nerdy!! 

These are checkerbloom seedlings that we pulled out of our garden on our February 12th Garden Work Day. Here are pictures taken on March 8th. 

Both these sets were taken from the same clump with one big difference: 
A. These seedlings were kept outside.
B. These seedlings were kept inside.

See the difference? It's been just 24 days and B is way bigger. 

We've all heard that in the Winter, plants go to "sleep". But what does that mean? 

It's called "dormancy". Cold temperatures slow down plant metabolism and growth as a protective measure - new leaves and flowers are especially vulnerable to frost damage. Lower temperatures are necessary to stimulate specific growth hormones, so it's not a bad thing. But sustained cold temperatures are keeping our plants pretty small. 

(Send these plants some warm thoughts! These specific plants will get bigger eventually and will be sent home with Volunteers to show our Thanks!!)

![IMG_5380](https://user-images.githubusercontent.com/2887265/223790611-2a4321c9-aab7-442b-84f8-611df0db2c9b.jpg)

![IMG_5378](https://user-images.githubusercontent.com/2887265/223790584-a6fc3b26-2497-4de0-854f-fce0cccdd210.jpg)

**Comment by kaycix** [comment]
It took me an embarrassingly long time to create this Volunteer flyer using a free template in the app Canva. 

Up to you if you want to use it. 

Basically, something like this. Tweak text as you want:

Calling all Volunteers! 
We would love to have your help this Sunday as we are really pushing to get beautiful annuals potted and settled in before our Spring Sale in May! 

First-time Volunteers please RSVP at northcoastcnps@gmail.com
Volunteer Info available via link in the bio.

If it's rainy, we'll be working in the hoop house! Rain gear is not required. 

All tools and training provided. 
Drop-in hours between 10a - 1p. You are not required to stay the whole time, come for however long you can. Clean-up generally starts at around 12:30p. 

![4286B801-29E5-447D-B13B-40C0AC234B6C](https://user-images.githubusercontent.com/2887265/225410276-63121479-8890-47b9-be48-fe2647b18e8d.PNG)

**Comment by CMK813** [comment]
> --- Not Yet Posted --- Maybe Tuesday, March 21st?
> 
> ### Post Idea:
> Let's get a little nerdy!!
> 
> These are checkerbloom seedlings that we pulled out of our garden on our February 12th Garden Work Day. Here are pictures taken on March 8th.
> 
> Both these sets were taken from the same clump with one big difference: A. These seedlings were kept outside. B. These seedlings were kept inside.
> 
> See the difference? It's been just 24 days and B is way bigger.
> 
> We've all heard that in the Winter, plants go to "sleep". But what does that mean?
> 
> It's called "dormancy". Cold temperatures slow down plant metabolism and growth as a protective measure - new leaves and flowers are especially vulnerable to frost damage. Lower temperatures are necessary to stimulate specific growth hormones, so it's not a bad thing. But sustained cold temperatures are keeping our plants pretty small.
> 
> (Send these plants some warm thoughts! These specific plants will get bigger eventually and will be sent home with Volunteers to show our Thanks!!)
> 
> ![IMG_5380](https://user-images.githubusercontent.com/2887265/223790611-2a4321c9-aab7-442b-84f8-611df0db2c9b.jpg)
> 
> ![IMG_5378](https://user-images.githubusercontent.com/2887265/223790584-a6fc3b26-2497-4de0-854f-fce0cccdd210.jpg)

Possible hashtags: #sidalcea #citizenscience #nativeplantcultivation #seedlings #plant science #plantnerd #plantnerdsunite
(~5+ hashtags/post is supposedly best...)
